services:
  - type: web
    name: kitchen-dashboard
    env: python
    plan: free
    startCommand: "python app.py"
    envVars:
      - key: POSTER_TOKEN
        sync: false
      - key: CHOICE_TOKEN   # üîë –¥–æ–±–∞–≤–ª—è–µ–º —Å—é–¥–∞
        sync: false
